#!/bin/bash
LOG_PATH=/d/DATA/TEAM_1731/_AUTO_LOGS/BATTLEFIELD
scp admin@10.17.31.2:/home/lvuser/PATH-FOLLOWER-LOGS.csv.prev $LOG_PATH
mv $LOG_PATH/PATH-FOLLOWER-LOGS.csv.prev $LOG_PATH/_UNPROCESSED_PATH-FOLLOWER-LOGS.csv
